// src/components/common/SortFilter.tsx
'use client';

import React, { Suspense } from 'react';
import { useRouter, usePathname, useSearchParams } from 'next/navigation';
import { cn } from '@/src/lib/utils';
import { Clock, History, ChevronDown } from 'lucide-react';

function SortFilterContent() {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();

  const currentSort = (searchParams.get('sort') === 'oldest' ? 'oldest' : 'newest') as 'newest' | 'oldest';

  const handleSortChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const newSort = e.target.value;
    const params = new URLSearchParams(searchParams.toString());
    
    if (newSort === 'newest') {
      params.delete('sort');
    } else {
      params.set('sort', newSort);
    }
    
    router.push(`${pathname}?${params.toString()}`, { scroll: false });
  };

  return (
    <div className="relative group min-w-[140px]">
      <div className="absolute left-4 top-1/2 -translate-y-1/2 pointer-events-none text-primary/60 group-hover:text-primary transition-colors flex items-center">
        {currentSort === 'newest' ? <Clock className="w-4 h-4" /> : <History className="w-4 h-4" />}
      </div>
      <select
        value={currentSort}
        onChange={handleSortChange}
        suppressHydrationWarning
        className={cn(
          "w-full pl-11 pr-10 py-2.5 rounded-2xl appearance-none cursor-pointer",
          "bg-surface-container-low border border-outline-variant/10 text-on-surface text-sm font-label font-medium",
          "hover:bg-surface-container-high hover:border-primary/20 transition-all duration-300",
          "focus:outline-none focus:ring-2 focus:ring-primary/20 shadow-sm"
        )}
      >
        <option value="newest">Terbaru</option>
        <option value="oldest">Terlama</option>
      </select>
      <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-on-surface-variant/40 flex items-center">
        <ChevronDown className="w-4 h-4" />
      </div>
    </div>
  );
}

export default function SortFilter() {
  return (
    <Suspense fallback={
      <div className="h-11 w-40 animate-pulse bg-surface-container-low border border-outline-variant/10 rounded-2xl"></div>
    }>
      <SortFilterContent />
    </Suspense>
  );
}

// src/lib/components/common/SortFilter.svelte
<script lang="ts">
	import { Clock, History, ChevronDown } from 'lucide-svelte';
	import { goto } from '$app/navigation';
	import { page } from '$app/state';
	import { cn } from '$lib/utils';

	const currentSort = $derived(page.url.searchParams.get('sort') === 'oldest' ? 'oldest' : 'newest');

	async function handleSortChange(e: Event) {
		const newSort = (e.currentTarget as HTMLSelectElement).value;
		const params = new URLSearchParams(page.url.searchParams);
		if (newSort === 'newest') {
			params.delete('sort');
		} else {
			params.set('sort', newSort);
		}
		const qs = params.toString();
		await goto(`${page.url.pathname}${qs ? `?${qs}` : ''}`, { replaceState: true });
	}
</script>

<div class="relative group min-w-[140px]">
	<div
		class="absolute left-4 top-1/2 -translate-y-1/2 pointer-events-none text-primary/60 group-hover:text-primary transition-colors flex items-center"
	>
		{#if currentSort === 'newest'}
			<Clock class="w-4 h-4" />
		{:else}
			<History class="w-4 h-4" />
		{/if}
	</div>
	<select
		value={currentSort}
		onchange={handleSortChange}
		class={cn(
			'w-full pl-11 pr-10 py-2.5 rounded-2xl appearance-none cursor-pointer',
			'bg-surface-container-low border border-outline-variant/10 text-on-surface text-sm font-label font-medium',
			'hover:bg-surface-container-high hover:border-primary/20 transition-all duration-300',
			'focus:outline-none focus:ring-2 focus:ring-primary/20 shadow-sm'
		)}
	>
		<option value="newest">Terbaru</option>
		<option value="oldest">Terlama</option>
	</select>
	<div class="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none text-on-surface-variant/40 flex items-center">
		<ChevronDown class="w-4 h-4" />
	</div>
</div>
