// src/routes/(public)/blog/+page.svelte
<script lang="ts">
	import type { PageProps } from './$types';
	import BlogScrollArea from '$lib/components/blog/BlogScrollArea.svelte';
	import JsonLd from '$lib/components/common/JsonLd.svelte';
	import BackButton from '$lib/components/common/BackButton.svelte';

	let { data }: PageProps = $props();

	const blogSchema = {
		'@context': 'https://schema.org',
		'@type': 'Blog',
		'@id': 'https://www.dimassfeb.com/blog#blog',
		name: 'Blog & Insights — Dimas Febriyanto',
		url: 'https://www.dimassfeb.com/blog',
		description: 'Articles about Flutter, Golang, mobile development, and backend engineering.',
		author: {
			'@type': 'Person',
			'@id': 'https://www.dimassfeb.com/#person',
			name: 'Dimas Febriyanto',
		},
		inLanguage: 'id-ID',
	};
</script>

<svelte:head>
	<title>Blog & Insights | Dimas Febriyanto — Software Engineer</title>
	<meta
		name="description"
		content="Articles about Flutter, Golang, mobile development, and backend engineering by Dimas Febriyanto — Fullstack & Mobile Developer from Bekasi, Indonesia."
	/>
	<link rel="canonical" href="https://www.dimassfeb.com/blog" />
	<meta property="og:type" content="website" />
	<meta property="og:url" content="https://www.dimassfeb.com/blog" />
	<meta property="og:title" content="Blog & Insights | Dimas Febriyanto — Software Engineer" />
	<meta
		property="og:description"
		content="Articles about Flutter, Golang, mobile development, and backend engineering by Dimas Febriyanto."
	/>
	<meta property="og:site_name" content="Dimas Febriyanto" />
	<meta property="og:image" content="https://www.dimassfeb.com/og-image.png" />
	<meta property="og:image:width" content="1200" />
	<meta property="og:image:height" content="630" />
	<meta property="og:image:alt" content="Blog & Insights — Dimas Febriyanto" />
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:title" content="Blog & Insights | Dimas Febriyanto" />
	<meta name="twitter:description" content="Articles about Flutter, Golang, mobile development, and backend engineering by Dimas Febriyanto." />
	<meta name="twitter:image" content="https://www.dimassfeb.com/og-image.png" />
</svelte:head>

<JsonLd schema={blogSchema} />

<main class="min-h-screen pt-32 pb-20 px-6 sm:px-10 max-w-7xl mx-auto">
	<div class="mb-10">
		<BackButton href="/#blog" />
	</div>
	<div class="space-y-4 mb-16">
		<h1 class="font-headline text-5xl sm:text-7xl font-bold text-on-surface">
			Blog & <span class="text-primary">Insights</span>
		</h1>
		<p class="font-body text-xl text-on-surface-variant max-w-2xl">
			Exploring web technology, design patterns, and life as a developer.
		</p>
	</div>

	{#if data.blogs.length > 0}
		<BlogScrollArea
			initialBlogs={data.blogs}
			initialNextCursor={data.nextCursor}
			initialHasMore={data.hasMore}
			batchSize={data.limit}
		/>
	{:else}
		<div class="text-center py-40 bg-surface-container-low rounded-[3rem] border border-dashed border-outline-variant/20">
			<p class="font-body text-on-surface-variant italic">No stories published yet. Stay tuned!</p>
		</div>
	{/if}
</main>

// app/blog/page.tsx
import React from 'react';
import { BlogService } from '@/src/services/blog.service';
import BlogScrollArea from '@/src/components/blog/BlogScrollArea';
import type { Metadata } from "next";
import { headers } from 'next/headers';
import JsonLd from '@/src/components/common/JsonLd';
import BackButton from '@/src/components/common/BackButton';

const BASE_URL = "https://www.dimassfeb.com";

export const metadata: Metadata = {
  title: "Blog & Insights",
  description:
    "Articles about Flutter, Golang, mobile development, and backend engineering by Dimas Febriyanto — Software Engineer from Bekasi, Indonesia.",
  alternates: {
    canonical: `${BASE_URL}/blog`,
  },
  openGraph: {
    type: "website",
    url: `${BASE_URL}/blog`,
    title: "Blog & Insights | Dimas Febriyanto",
    description:
      "Articles about Flutter, Golang, mobile development, and backend engineering.",
    siteName: "Dimas Febriyanto",
    images: [{ url: "/og-image.jpg", width: 1200, height: 630, alt: "Blog & Insights" }],
  },
};

export const revalidate = 3600; // Revalidate every hour

export default async function BlogListPage() {
  const headersList = await headers();
  const userAgent = headersList.get('user-agent') || '';
  const isMobile = /mobile|android|iphone|ipad/i.test(userAgent);
  const limit = isMobile ? 6 : 9;

  const { blogs, nextCursor, hasMore } = await BlogService.getAllBlogs({ onlyPublished: true, limit });

  const blogSchema = {
    "@context": "https://schema.org",
    "@type": "Blog",
    "@id": "https://www.dimassfeb.com/blog#blog",
    name: "Blog & Insights — Dimas Febriyanto",
    url: "https://www.dimassfeb.com/blog",
    description:
      "Articles about Flutter, Golang, mobile development, and backend engineering.",
    author: {
      "@type": "Person",
      "@id": "https://www.dimassfeb.com/#person",
      name: "Dimas Febriyanto",
    },
    inLanguage: "id-ID",
  };

  return (
    <div className="min-h-screen pt-32 pb-20 px-6 sm:px-10 max-w-7xl mx-auto">
      <JsonLd schema={blogSchema} />
      <div className="mb-10">
        <BackButton href="/#blog" />
      </div>
      <div className="space-y-4 mb-16">
        <h1 className="font-headline text-5xl sm:text-7xl font-bold text-on-surface">
          Blog & <span className="text-primary">Insights</span>
        </h1>
        <p className="font-body text-xl text-on-surface-variant max-w-2xl">
          Exploring web technology, design patterns, and life as a developer.
        </p>
      </div>

      {blogs.length > 0 ? (
        <BlogScrollArea 
          initialBlogs={blogs} 
          initialNextCursor={nextCursor} 
          initialHasMore={hasMore} 
          batchSize={limit}
        />
      ) : (
        <div className="text-center py-40 bg-surface-container-low rounded-[3rem] border border-dashed border-outline-variant/20">
          <p className="font-body text-on-surface-variant italic">No stories published yet. Stay tuned!</p>
        </div>
      )}
    </div>
  );
}
