// src/lib/components/sections/ContactSection.svelte
<script lang="ts">
	import { ExternalLink, Mail } from 'lucide-svelte';
	import SocialIcon from '../ui/SocialIcon.svelte';

	interface ContactData {
		headline: string;
		description: string;
		email: string;
		linkedin_url: string;
		github_url?: string;
		instagram_url?: string;
		twitter_url?: string;
	}

	let { data }: { data: ContactData } = $props();
</script>

<section class="pt-16 xs:pt-24 lg:pt-32 pb-12 text-center relative overflow-hidden">
	<div class="max-w-3xl mx-auto px-6">
		<h2 class="font-headline text-3xl xs:text-4xl lg:text-5xl font-bold tracking-tight text-on-surface mb-6">
			{data.headline}
		</h2>
		<p class="font-body text-base xs:text-lg md:text-xl text-on-surface-variant mb-12 leading-relaxed font-light">
			{data.description}
		</p>
		<div class="flex flex-col sm:flex-row items-center justify-center gap-6 mb-12">
			<a
				class="w-full sm:w-auto px-8 py-4 rounded-full bg-primary text-white font-label font-medium tracking-wide transition-all duration-300 hover:shadow-[0_8px_30px_rgb(0,62,199,0.25)] hover:-translate-y-1 active:translate-y-0"
				href={`mailto:${data.email}`}
			>
				Send an Email
			</a>
			<a
				class="w-full sm:w-auto px-8 py-4 rounded-full bg-surface-container-highest text-on-surface font-label font-medium tracking-wide transition-all duration-300 hover:bg-surface-variant flex items-center justify-center gap-2"
				href={data.linkedin_url}
				rel="noopener noreferrer"
				target="_blank"
			>
				LinkedIn Profile
				<ExternalLink class="w-3.5 h-3.5" />
			</a>
		</div>
		<div class="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-surface-container-low border border-outline-variant/20 mb-12">
			<Mail class="w-4 h-4 text-on-surface-variant" />
			<span class="text-on-surface-variant font-label text-sm tracking-wide">
				{data.email}
			</span>
		</div>

		<!-- Social Links Row -->
		<div class="flex items-center justify-center gap-6">
			{#if data.linkedin_url}
				<a
					href={data.linkedin_url}
					target="_blank"
					rel="noopener noreferrer"
					class="p-3 rounded-2xl bg-surface-container-low border border-outline-variant/10 text-on-surface-variant hover:text-primary hover:border-primary/30 transition-all hover:-translate-y-1"
					title="LinkedIn"
				>
					<SocialIcon platform="linkedin" className="w-6 h-6" />
				</a>
			{/if}
			{#if data.github_url}
				<a
					href={data.github_url}
					target="_blank"
					rel="noopener noreferrer"
					class="p-3 rounded-2xl bg-surface-container-low border border-outline-variant/10 text-on-surface-variant hover:text-primary hover:border-primary/30 transition-all hover:-translate-y-1"
					title="GitHub"
				>
					<SocialIcon platform="github" className="w-6 h-6" />
				</a>
			{/if}
			{#if data.instagram_url}
				<a
					href={data.instagram_url}
					target="_blank"
					rel="noopener noreferrer"
					class="p-3 rounded-2xl bg-surface-container-low border border-outline-variant/10 text-on-surface-variant hover:text-primary hover:border-primary/30 transition-all hover:-translate-y-1"
					title="Instagram"
				>
					<SocialIcon platform="instagram" className="w-6 h-6" />
				</a>
			{/if}
			{#if data.twitter_url}
				<a
					href={data.twitter_url}
					target="_blank"
					rel="noopener noreferrer"
					class="p-3 rounded-2xl bg-surface-container-low border border-outline-variant/10 text-on-surface-variant hover:text-primary hover:border-primary/30 transition-all hover:-translate-y-1"
					title="Twitter / X"
				>
					<SocialIcon platform="twitter" className="w-6 h-6" />
				</a>
			{/if}
		</div>
	</div>
</section>

// src/components/sections/ContactSection.tsx
import React from "react";
import { Mail, ExternalLink } from "lucide-react";
import SocialIcon from "../ui/SocialIcon";

interface ContactData {
  headline: string;
  description: string;
  email: string;
  linkedin_url: string;
  github_url?: string;
  instagram_url?: string;
  twitter_url?: string;
}

interface ContactSectionProps {
  data: ContactData;
}

const ContactSection: React.FC<ContactSectionProps> = ({ data }) => {
  return (
    <section className="pt-16 xs:pt-24 lg:pt-32 pb-12 text-center relative overflow-hidden">
      <div className="max-w-3xl mx-auto px-6">
        <h2 className="font-headline text-3xl xs:text-4xl lg:text-5xl font-bold tracking-tight text-on-surface mb-6">
          {data.headline}
        </h2>
        <p className="font-body text-base xs:text-lg md:text-xl text-on-surface-variant mb-12 leading-relaxed font-light">
          {data.description}
        </p>
        <div className="flex flex-col sm:flex-row items-center justify-center gap-6 mb-12">
          <a
            className="w-full sm:w-auto px-8 py-4 rounded-full bg-primary text-white font-label font-medium tracking-wide transition-all duration-300 hover:shadow-[0_8px_30px_rgb(0,62,199,0.25)] hover:-translate-y-1 active:translate-y-0"
            href={`mailto:${data.email}`}
          >
            Send an Email
          </a>
          <a
            className="w-full sm:w-auto px-8 py-4 rounded-full bg-surface-container-highest text-on-surface font-label font-medium tracking-wide transition-all duration-300 hover:bg-surface-variant flex items-center justify-center gap-2"
            href={data.linkedin_url}
            rel="noopener noreferrer"
            target="_blank"
          >
            LinkedIn Profile
            <ExternalLink className="w-3.5 h-3.5" />
          </a>
        </div>
        <div className="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-surface-container-low border border-outline-variant/20 mb-12">
          <Mail className="w-4 h-4 text-on-surface-variant" />
          <span className="text-on-surface-variant font-label text-sm tracking-wide">
            {data.email}
          </span>
        </div>

        {/* Social Links Row */}
        <div className="flex items-center justify-center gap-6">
          {data.linkedin_url && (
            <a
              href={data.linkedin_url}
              target="_blank"
              rel="noopener noreferrer"
              className="p-3 rounded-2xl bg-surface-container-low border border-outline-variant/10 text-on-surface-variant hover:text-primary hover:border-primary/30 transition-all hover:-translate-y-1"
              title="LinkedIn"
            >
              <SocialIcon platform="linkedin" className="w-6 h-6" />
            </a>
          )}
          {data.github_url && (
            <a
              href={data.github_url}
              target="_blank"
              rel="noopener noreferrer"
              className="p-3 rounded-2xl bg-surface-container-low border border-outline-variant/10 text-on-surface-variant hover:text-primary hover:border-primary/30 transition-all hover:-translate-y-1"
              title="GitHub"
            >
              <SocialIcon platform="github" className="w-6 h-6" />
            </a>
          )}
          {data.instagram_url && (
            <a
              href={data.instagram_url}
              target="_blank"
              rel="noopener noreferrer"
              className="p-3 rounded-2xl bg-surface-container-low border border-outline-variant/10 text-on-surface-variant hover:text-primary hover:border-primary/30 transition-all hover:-translate-y-1"
              title="Instagram"
            >
              <SocialIcon platform="instagram" className="w-6 h-6" />
            </a>
          )}
          {data.twitter_url && (
            <a
              href={data.twitter_url}
              target="_blank"
              rel="noopener noreferrer"
              className="p-3 rounded-2xl bg-surface-container-low border border-outline-variant/10 text-on-surface-variant hover:text-primary hover:border-primary/30 transition-all hover:-translate-y-1"
              title="Twitter / X"
            >
              <SocialIcon platform="twitter" className="w-6 h-6" />
            </a>
          )}
        </div>
      </div>
    </section>
  );
};

export default ContactSection;
