// src/lib/components/sections/ExperienceSection.svelte
<script lang="ts">
	import ExperienceItem from '../ui/ExperienceItem.svelte';

	interface Experience {
		id?: number;
		role: string;
		company: string;
		start_date: string | Date;
		end_date: string | Date | null;
		description: string[];
		tags?: string[];
	}

	let { experiences: initialExperiences }: { experiences: Experience[] } = $props();

	const initialSnapshot = () => initialExperiences;
	let experiences = $state<Experience[]>(initialSnapshot());
	let offset = $state(initialSnapshot().length);
	let isLoading = $state(false);
	let hasMore = $state(true);
	let observerTarget = $state<HTMLDivElement | null>(null);
	const PAGE_SIZE = 4;

	const groupedExperiences = $derived(
		experiences.reduce<{ company: string; roles: Experience[] }[]>((groups, exp) => {
			const existingGroup = groups.find((g) => g.company === exp.company);
			if (existingGroup) {
				existingGroup.roles.push(exp);
			} else {
				groups.push({ company: exp.company, roles: [exp] });
			}
			return groups;
		}, []),
	);

	async function loadMoreExperiences() {
		if (isLoading || !hasMore) return;
		isLoading = true;
		try {
			const response = await fetch(`/api/experience?limit=${PAGE_SIZE}&offset=${offset}`);
			const result = await response.json();
			if (result.status === 200 && result.data) {
				const newExperiences = result.data;
				if (newExperiences.length < PAGE_SIZE) {
					hasMore = false;
				}
				experiences = [...experiences, ...newExperiences];
				offset += newExperiences.length;
			} else {
				hasMore = false;
			}
		} catch (error) {
			console.error('Error loading more experiences:', error);
			hasMore = false;
		} finally {
			isLoading = false;
		}
	}

	$effect(() => {
		if (!observerTarget) return;
		const observer = new IntersectionObserver(
			(entries) => {
				if (entries[0].isIntersecting && hasMore) {
					loadMoreExperiences();
				}
			},
			{ threshold: 0.1 },
		);
		observer.observe(observerTarget);
		return () => observer.disconnect();
	});
</script>

<section id="experience" class="pt-12 xs:pt-16 lg:pt-24 min-h-[400px]">
	<div class="flex flex-col md:flex-row md:items-end justify-between mb-12 xs:mb-16 gap-6">
		<div class="max-w-xl">
			<h2 class="font-headline text-3xl xs:text-4xl lg:text-5xl font-bold tracking-tight text-on-surface mb-4">
				Professional Journey.
			</h2>
			<p class="font-body text-on-surface-variant text-base xs:text-lg">
				Experience everything I've worked on throughout my career in software development.
			</p>
		</div>
	</div>

	<div class="flex flex-col gap-12">
		{#each groupedExperiences as group}
			<ExperienceItem company={group.company} roles={group.roles} />
		{/each}
	</div>

	<div bind:this={observerTarget} class="h-20 flex items-center justify-center mt-12">
		{#if isLoading}
			<div class="flex flex-col items-center gap-3">
				<div class="w-8 h-8 border-4 border-primary/20 border-t-primary rounded-full animate-spin"></div>
				<p class="text-xs font-medium text-zinc-400 animate-pulse uppercase tracking-widest">
					Loading More Experience
				</p>
			</div>
		{/if}
		{#if !hasMore && experiences.length > 0}
			<div class="flex flex-col items-center gap-2 py-8">
				<div class="h-px w-12 bg-zinc-200"></div>
				<p class="text-zinc-400 text-sm font-medium">
					End of Professional Journey
				</p>
			</div>
		{/if}
	</div>
</section>

// src/components/sections/ExperienceSection.tsx
"use client";

import React from "react";
import ExperienceItem from "../ui/ExperienceItem";

interface Experience {
  id?: number;
  role: string;
  company: string;
  start_date: string | Date;
  end_date: string | Date | null;
  description: string[];
  tags?: string[];
}

interface ExperienceSectionProps {
  experiences: Experience[];
}

const ExperienceSection: React.FC<ExperienceSectionProps> = ({
  experiences: initialExperiences,
}) => {
  const [experiences, setExperiences] =
    React.useState<Experience[]>(initialExperiences);
  const [offset, setOffset] = React.useState(initialExperiences.length);
  const [isLoading, setIsLoading] = React.useState(false);
  const [hasMore, setHasMore] = React.useState(true);
  const observerTarget = React.useRef<HTMLDivElement>(null);
  const PAGE_SIZE = 4;

  const groupedExperiences = React.useMemo(() => {
    const groups: {
      company: string;
      roles: Experience[];
    }[] = [];

    experiences.forEach((exp) => {
      const existingGroup = groups.find((g) => g.company === exp.company);
      if (existingGroup) {
        existingGroup.roles.push(exp);
      } else {
        groups.push({
          company: exp.company,
          roles: [exp],
        });
      }
    });

    return groups;
  }, [experiences]);

  const loadMoreExperiences = React.useCallback(async () => {
    if (isLoading || !hasMore) return;

    setIsLoading(true);
    try {
      const response = await fetch(
        `/api/experience?limit=${PAGE_SIZE}&offset=${offset}`,
      );
      const result = await response.json();

      if (result.status === 200 && result.data) {
        const newExperiences = result.data;

        if (newExperiences.length < PAGE_SIZE) {
          setHasMore(false);
        }
        setExperiences((prev) => [...prev, ...newExperiences]);
        setOffset((prev) => prev + newExperiences.length);
      } else {
        setHasMore(false);
      }
    } catch (error) {
      console.error("Error loading more experiences:", error);
      setHasMore(false);
    } finally {
      setIsLoading(false);
    }
  }, [offset, isLoading, hasMore]);

  React.useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries[0].isIntersecting && hasMore) {
          loadMoreExperiences();
        }
      },
      { threshold: 0.1 },
    );

    if (observerTarget.current) {
      observer.observe(observerTarget.current);
    }

    return () => observer.disconnect();
  }, [loadMoreExperiences, hasMore]);

  return (
    <section id="experience" className="pt-12 xs:pt-16 lg:pt-24 min-h-[400px]">
      <div className="flex flex-col md:flex-row md:items-end justify-between mb-12 xs:mb-16 gap-6">
        <div className="max-w-xl">
          <h2 className="font-headline text-3xl xs:text-4xl lg:text-5xl font-bold tracking-tight text-on-surface mb-4">
            Professional Journey.
          </h2>
          <p className="font-body text-on-surface-variant text-base xs:text-lg">
            Experience everything I've worked on throughout my career in
            software development.
          </p>
        </div>
      </div>

      <div className="flex flex-col gap-12">
        {groupedExperiences.map((group, index) => (
          <ExperienceItem
            key={`${group.company}-${index}`}
            company={group.company}
            roles={group.roles}
          />
        ))}
      </div>

      {/* Sentinel Element for Infinite Scroll */}
      {true && (
        <div
          ref={observerTarget}
          className="h-20 flex items-center justify-center mt-12"
        >
          {isLoading && (
            <div className="flex flex-col items-center gap-3">
              <div className="w-8 h-8 border-4 border-primary/20 border-t-primary rounded-full animate-spin" />
              <p className="text-xs font-medium text-zinc-400 animate-pulse uppercase tracking-widest">
                Loading More Experience
              </p>
            </div>
          )}
          {!hasMore && experiences.length > 0 && (
            <div className="flex flex-col items-center gap-2 py-8">
              <div className="h-px w-12 bg-zinc-200" />
              <p className="text-zinc-400 text-sm font-medium">
                End of Professional Journey
              </p>
            </div>
          )}
        </div>
      )}
    </section>
  );
};

export default ExperienceSection;
