// src/lib/components/projects/gallery/GalleryGrid.svelte
<script lang="ts">
	import GalleryItem from './GalleryItem.svelte';
	import ImageModal from './ImageModal.svelte';

	let { screenshots, projectTitle }: { screenshots: string[]; projectTitle: string } = $props();

	let selectedIndex = $state<number | null>(null);

	function handleNext() {
		if (selectedIndex === null) return;
		selectedIndex = (selectedIndex + 1) % screenshots.length;
	}

	function handlePrev() {
		if (selectedIndex === null) return;
		selectedIndex = (selectedIndex - 1 + screenshots.length) % screenshots.length;
	}
</script>

<div class="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
	{#each screenshots as img, i}
		<GalleryItem imageUrl={img} index={i} {projectTitle} priority={i === 0} onclick={() => (selectedIndex = i)} />
	{/each}
</div>

<ImageModal
	isOpen={selectedIndex !== null}
	onClose={() => (selectedIndex = null)}
	imageUrl={selectedIndex !== null ? screenshots[selectedIndex] : ''}
	altText={selectedIndex !== null ? `${projectTitle} screenshot ${selectedIndex + 1}` : ''}
	onNext={handleNext}
	onPrev={handlePrev}
	hasMultiple={screenshots.length > 1}
/>

// src/components/projects/gallery/GalleryGrid.tsx
"use client";

import { useState } from "react";
import GalleryItem from "./GalleryItem";
import ImageModal from "./ImageModal";

interface GalleryGridProps {
  screenshots: string[];
  projectTitle: string;
}

export default function GalleryGrid({
  screenshots,
  projectTitle,
}: GalleryGridProps) {
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null);

  const handleOpen = (index: number) => setSelectedIndex(index);
  const handleClose = () => setSelectedIndex(null);

  const handleNext = () => {
    if (selectedIndex === null) return;
    setSelectedIndex((prev) => (prev! + 1) % screenshots.length);
  };

  const handlePrev = () => {
    if (selectedIndex === null) return;
    setSelectedIndex(
      (prev) => (prev! - 1 + screenshots.length) % screenshots.length
    );
  };

  return (
    <>
      <div className="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
        {screenshots.map((img, i) => (
          <GalleryItem
            key={i}
            imageUrl={img}
            index={i}
            projectTitle={projectTitle}
            priority={i === 0}
            onClick={() => handleOpen(i)}
          />
        ))}
      </div>

      <ImageModal
        isOpen={selectedIndex !== null}
        onClose={handleClose}
        imageUrl={selectedIndex !== null ? screenshots[selectedIndex] : ""}
        altText={
          selectedIndex !== null
            ? `${projectTitle} screenshot ${selectedIndex + 1}`
            : ""
        }
        onNext={handleNext}
        onPrev={handlePrev}
        hasMultiple={screenshots.length > 1}
      />
    </>
  );
}
